pipeline {
    agent any
    environment {
        REGISTRY_NAME               = credentials('REGISTRY_NAME')
        DOCKER_REGISTRY_USERNAME    = credentials('DOCKER_REGISTRY_USERNAME')
        DOCKER_REGISTRY_PASSWORD    = credentials('DOCKER_REGISTRY_PASSWORD')
    }

    stages {
        stage('git-checkout') {
            steps {
                dir('app_code') {
                    git url: 'https://github.com/hoabka/nodejs-demo.git'
                }
            }
        }
        stage('docker-build/push-registry') {
            steps {
		echo "Docker registry username is ${DOCKER_REGISTRY_USERNAME}"
		echo "Docker registry password is ${DOCKER_REGISTRY_PASSWORD}"
		echo "Registry name is ${REGISTRY_NAME}"
                sh '''#!/usr/bin/env bash
                cd app_code
		whoami
                docker login -u cuongnt260601 -p Cuong260601a@
                docker build --tag "cuongnt260601/nodejs-demo:${BUILD_NUMBER}" .
                docker push "cuongnt260601/nodejs-demo:${BUILD_NUMBER}"
                '''
            }
        }
    }
}
